### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by simonhowden3010** [2xAA/ym2149synth-web-editor#7]
Hey, just letting you know I tested this on Windows 10 in the latest version of chrome and it never connects to a device

Followed the exact steps you state in the readme, and device is fine because its been tested using renoise (closed renoise before opening in your app)

Apologies if you're already aware of this

Let me know if you need any info

Thanks

**Comment by 2xAA** [comment]
Hi @simonhowden3010,

Thanks for the bug report. The manufacturer returned by the WebMIDI API on Windows seems to now be different than other platforms.

MIDI on Windows has always been a struggle, this is just adding to the frustration.

The check in `src/application/is-synth.js` should either be updated with the new string returned WebMIDI on Windows or we should remove the manufacturer check altogether.

**Comment by TimPietrusky** [comment]
@2xAA I think every check on Windows related to WebMIDI is useless as this is not working in a consistent way since forever.

**Comment by simonhowden3010** [comment]
Could a mitigation be to only remove the check if on windows?

**Comment by 2xAA** [comment]
I think the manufacturer check should just be dropped. There can't be that many devices out there with the name "YM2149".

I can jump on this soon, I'll update the issue once I've resolved the problem.

**Comment by 2xAA** [comment]
Hi @simonhowden3010 - the latest changes on master fix this.
I also discovered I had some abandoned additions for people who built the synth DIY and didn't name it "YM2149", so I've added those in too.

You can find the latest version live here: https://2xaa.github.io/ym2149synth-web-editor/

**Comment by simonhowden3010** [comment]
Thanks, works like a dream
